In [30]:
#!/usr/bin/env python3
"""
Алгоритма Нидлмана-Вунша.
"""

import time
import os


def clear_screen():
    """Очищает экран"""
    os.system('clear' if os.name == 'posix' else 'cls')


def print_matrix(seq1, seq2, dp, current_i=None, current_j=None, step_info=""):
    """
    Печатает матрицу с анимацией текущей ячейки
    """
    clear_screen()

    print("=" * 70)
    print("АЛГОРИТМ НИДЛМАНА-ВУНША - ПОШАГОВОЕ ЗАПОЛНЕНИЕ")
    print("=" * 70)
    print(f"Seq1: {seq1}")
    print(f"Seq2: {seq2}")
    if step_info:
        print(f"Шаг: {step_info}")
    print()

    # Заголовок
    print("     ", end="")
    for j in range(len(dp[0])):
        if j == 0:
            print("   ", end="")
        else:
            print(f"  {seq2[j-1]}", end="")
    print()

    # Строки матрицы
    for i in range(len(dp)):
        if i == 0:
            print("   ", end="")
        else:
            print(f" {seq1[i-1]} ", end="")

        for j in range(len(dp[0])):
            # Выделяем текущую ячейку
            if current_i == i and current_j == j:
                print(f"[{dp[i][j]:2}]", end="")
            else:
                print(f" {dp[i][j]:2} ", end="")
        print()

    print("=" * 70)


def needleman_wunsch(seq1, seq2, match=2, mismatch=-1, gap=-1):
    """
    Алгоритма Нидлмана-Вунша
    """
    n, m = len(seq1), len(seq2)


    dp = [[0] * (m+1) for _ in range(n+1)]

    for i in range(n+1):
        dp[i][0] = i * gap
    for j in range(m+1):
        dp[0][j] = j * gap

    print_matrix(seq1, seq2, dp, step_info="Инициализация")
    time.sleep(2)

    for i in range(1, n+1):
        for j in range(1, m+1):
            print_matrix(seq1, seq2, dp, current_i=i, current_j=j,
                                step_info=f"Заполнение ячейки ({i},{j})")

            match_score = dp[i-1][j-1] + (match if seq1[i-1] == seq2[j-1] else mismatch)
            delete = dp[i-1][j] + gap
            insert = dp[i][j-1] + gap

            print(f"\nРасчет для {seq1[i-1]} vs {seq2[j-1]}:")
            print(f"↖ Совпадение: {dp[i-1][j-1]} + {match if seq1[i-1] == seq2[j-1] else '-1'} = {match_score}")
            print(f"↑ Удаление:   {dp[i-1][j]} + {gap} = {delete}")
            print(f"← Вставка:    {dp[i][j-1]} + {gap} = {insert}")

            dp[i][j] = max(match_score, delete, insert)

            print(f"Максимум: {dp[i][j]}")
            time.sleep(1.5)

    print_matrix(seq1, seq2, dp, step_info="Матрица заполнена")
    time.sleep(2)

    align1, align2 = "", ""
    i, j = n, m

    print("\nОБРАТНЫЙ ПРОХОД:")
    print("=" * 50)

    step = 1
    while i > 0 or j > 0:
        print(f"\nШаг {step}: Позиция ({i},{j})")

        if i > 0 and j > 0 and dp[i][j] == dp[i-1][j-1] + (match if seq1[i-1] == seq2[j-1] else mismatch):
            print(f"  ↖ Совпадение: {seq1[i-1]} = {seq2[j-1]}")
            align1 = seq1[i-1] + align1
            align2 = seq2[j-1] + align2
            i -= 1
            j -= 1
        elif i > 0 and dp[i][j] == dp[i-1][j] + gap:
            print(f"  ↑ Удаление: {seq1[i-1]} → -")
            align1 = seq1[i-1] + align1
            align2 = "-" + align2
            i -= 1
        else:
            print(f"  ← Вставка: - ← {seq2[j-1]}")
            align1 = "-" + align1
            align2 = seq2[j-1] + align2
            j -= 1

        print(f"  Выравнивание: {align1}")
        print(f"                {align2}")

        step += 1
        time.sleep(1)

    return align1, align2, dp


def main():
    """
    Демонстрация алгоритма
    """
    # Ваши последовательности
    seq1 = "GCATGCG"
    seq2 = "GATTACA"

    print("АЛГОРИТМ НИДЛМАНА-ВУНША")
    print("=" * 70)
    print(f"Последовательность 1: {seq1}")
    print(f"Последовательность 2: {seq2}")
    print("Параметры: match=2, mismatch=-1, gap=-1")
    print()

    result1, result2, matrix = needleman_wunsch(seq1, seq2)

    print("\n" + "=" * 70)
    print("ФИНАЛЬНЫЙ РЕЗУЛЬТАТ:")
    print("=" * 70)
    print(f"Выравнивание 1: {result1}")
    print(f"Выравнивание 2: {result2}")
    print(f"Общий score: {matrix[len(seq1)][len(seq2)]}")


if __name__ == "__main__":
    main()


АЛГОРИТМ НИДЛМАНА-ВУНША
Последовательность 1: GCATGCG
Последовательность 2: GATTACA
Параметры: match=2, mismatch=-1, gap=-1

АЛГОРИТМ НИДЛМАНА-ВУНША - ПОШАГОВОЕ ЗАПОЛНЕНИЕ
Seq1: GCATGCG
Seq2: GATTACA
Шаг: Инициализация

          G  A  T  T  A  C  A
     0  -1  -2  -3  -4  -5  -6  -7 
 G  -1   0   0   0   0   0   0   0 
 C  -2   0   0   0   0   0   0   0 
 A  -3   0   0   0   0   0   0   0 
 T  -4   0   0   0   0   0   0   0 
 G  -5   0   0   0   0   0   0   0 
 C  -6   0   0   0   0   0   0   0 
 G  -7   0   0   0   0   0   0   0 
АЛГОРИТМ НИДЛМАНА-ВУНША - ПОШАГОВОЕ ЗАПОЛНЕНИЕ
Seq1: GCATGCG
Seq2: GATTACA
Шаг: Заполнение ячейки (1,1)

          G  A  T  T  A  C  A
     0  -1  -2  -3  -4  -5  -6  -7 
 G  -1 [ 0]  0   0   0   0   0   0 
 C  -2   0   0   0   0   0   0   0 
 A  -3   0   0   0   0   0   0   0 
 T  -4   0   0   0   0   0   0   0 
 G  -5   0   0   0   0   0   0   0 
 C  -6   0   0   0   0   0   0   0 
 G  -7   0   0   0   0   0   0   0 

Расчет для G vs G:
↖ Совпадение: 0 + 2

# Домашнее задание

In [31]:
import numpy as np

In [32]:
# 1. Вам представлен код с реализацией алгоритма Нидлмана-Вунша. Функция needleman_wunsch принимает параметры: match=2, mismatch=-1, gap=-1
# поэксперементируйте с параметрами и посморите, как меняется выравнивание и score. Какие выводы можно сделать?

1. Влияние match

* Увеличение очков за совпадение (match) делает алгоритм более склонным к выбору выравниваний с большим количеством совпадений.
* Score выравнивания растёт, даже если приходится вставлять дополнительные пробелы для максимизации совпадений.


2. Влияние mismatch
* Более отрицательные значения mismatch повышают штраф за несовпадение.
* Алгоритм старается избегать несовпадений, иногда вставляя пробелы вместо прямого несовпадения.
* Score снижается при слишком жестком штрафе за несовпадение, если совпадений меньше.

3. Влияние gap
* Сильный отрицательный gap снижает количество вставок/удалений, делая выравнивание более «компактным».
* Слабый штраф за пробелы позволяет чаще вставлять дефисы для сохранения совпадений.
* Score может быть выше при умеренном значении gap, если оно позволяет гибко балансировать между совпадениями и вставками.

Таким образом,
* Высокий match + мягкий gap =>  длинные совпадения, иногда с дефисами.
* Сильный mismatch или gap => меньше дефисов и несовпадений, выравнивание более «жёсткое».

In [33]:
# 2. Используя numpy создайте матрицу 7 на 7

matrix1 = np.array([[7 * i + j + 1 for j in range(7)] for i in range(7)])
print(matrix1)
print()

matrix2 = np.zeros((7, 7))
print(matrix2)
print()

matrix3 = np.ones((7, 7))
print(matrix3)
print()

matrix4 = np.random.randint(0, 10, size=(7, 7))
print(matrix4)
print()

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]
 [22 23 24 25 26 27 28]
 [29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42]
 [43 44 45 46 47 48 49]]

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]

[[3 0 0 9 7 6 7]
 [8 3 7 8 3 8 0]
 [5 8 9 8 7 2 5]
 [3 1 0 7 3 8 2]
 [4 3 6 0 5 8 4]
 [4 1 0 5 2 3 9]
 [8 3 1 0 8 0 6]]



In [34]:
# 3. NumPy: создайтие диагональную матрицу, где по главной диагонали идут числа от 1 до 5

diagonal_matrix = np.diag(np.arange(1, 6))
print(diagonal_matrix)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [35]:
# 4. Напиши функцию, которая принимает матрицу и проверяет, является ли она единичной. В ответе возвращается True или False

def is_identity(x):
  identity_matrix = np.eye(x.shape[0])
  return np.array_equal(x, identity_matrix)

print(is_identity(np.eye(5)))
print(is_identity(np.array([[1, 0, 0],
                            [0, 1, 0],
                            [0, 0, 0]])))
print(is_identity(np.array([[1, 0, 1],
                            [0, 1, 0],
                            [0, 0, 1]])))

True
False
False
